<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="FactoryService" targetNamespace="http://www.globus.org/namespaces/GenericPortal/FactoryService/bindings" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:porttype="http://www.globus.org/namespaces/GenericPortal/FactoryService" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:import namespace="http://www.globus.org/namespaces/GenericPortal/FactoryService" location="Factory_flattened.wsdl"/>
  <wsdl:binding name="FactoryPortTypeSOAPBinding" type="porttype:FactoryPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="createResource">
      <soap:operation soapAction="http://www.globus.org/namespaces/GenericPortal/FactoryService/FactoryPortType/createResourceRequest"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>
